module com.spacecodee.healthproyect {
    requires javafx.controls;
    requires javafx.fxml;
    requires commons.dbcp2;
    requires java.sql;
    requires java.management;
    requires lombok;

    opens com.spacecodee.healthproyect to javafx.fxml;
    opens com.spacecodee.healthproyect.controllers.dashboard to javafx.fxml;
    opens com.spacecodee.healthproyect.controllers.top_bar to javafx.fxml;
    opens com.spacecodee.healthproyect.controllers.user_roles to javafx.fxml;
    opens com.spacecodee.healthproyect.controllers.modals to javafx.fxml;
    opens com.spacecodee.healthproyect.controllers.address to javafx.fxml;
    opens com.spacecodee.healthproyect.controllers.countries to javafx.fxml;
    opens com.spacecodee.healthproyect.controllers.cities to javafx.fxml;
    opens com.spacecodee.healthproyect.controllers.districs to javafx.fxml;
    opens com.spacecodee.healthproyect.controllers.users to javafx.fxml;
    opens com.spacecodee.healthproyect.controllers.add_modal to javafx.fxml;
    opens com.spacecodee.healthproyect.controllers.customers to javafx.fxml;
    opens com.spacecodee.healthproyect.controllers.reservation_appointments to javafx.fxml;
    opens com.spacecodee.healthproyect.controllers.type_reservations to javafx.fxml;
    opens com.spacecodee.healthproyect.controllers.menu to javafx.fxml;
    opens com.spacecodee.healthproyect.controllers.login to javafx.fxml;
    opens com.spacecodee.healthproyect.controllers.settings to javafx.fxml;
    opens com.spacecodee.healthproyect.dto.users_roles to javafx.base;
    opens com.spacecodee.healthproyect.dto.countries to javafx.base;
    opens com.spacecodee.healthproyect.dto.reservation_appointments to javafx.base;
    opens com.spacecodee.healthproyect.dto.type_reservations to javafx.base;
    opens com.spacecodee.healthproyect.converters.country to javafx.base;
    opens com.spacecodee.healthproyect.converters.address to javafx.base;
    opens com.spacecodee.healthproyect.converters.city to javafx.base;
    opens com.spacecodee.healthproyect.converters.district to javafx.base;
    opens com.spacecodee.healthproyect.converters.user to javafx.base;
    opens com.spacecodee.healthproyect.converters.customer to javafx.base;
    opens com.spacecodee.healthproyect.converters.reservation_appointments to javafx.base;
    exports com.spacecodee.healthproyect to javafx.graphics;
    exports com.spacecodee.healthproyect.dto.reservation_appointments;
    exports com.spacecodee.healthproyect.controllers.dashboard;
    exports com.spacecodee.healthproyect.controllers.user_roles;
    exports com.spacecodee.healthproyect.dto.customers;
    exports com.spacecodee.healthproyect.controllers.modals to javafx.fxml;
    exports com.spacecodee.healthproyect.controllers.address to javafx.fxml;
    exports com.spacecodee.healthproyect.controllers.countries to javafx.fxml;
    exports com.spacecodee.healthproyect.controllers.cities to javafx.fxml;
    exports com.spacecodee.healthproyect.controllers.districs to javafx.fxml;
    exports com.spacecodee.healthproyect.controllers.reservation_appointments to javafx.fxml;
    exports com.spacecodee.healthproyect.controllers.type_reservations to javafx.fxml;
    exports com.spacecodee.healthproyect.controllers.menu to javafx.fxml;
    exports com.spacecodee.healthproyect.controllers.settings to javafx.fxml;
    exports com.spacecodee.healthproyect.controllers.login to javafx.fxml;
}